# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nextver < Formula
  desc "A dead simple CLI tool that prints the next semantic version based on the last tag of your git repository"
  homepage "https://github.com/junk1tm/nextver"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/junk1tm/nextver/releases/download/v0.2.1/nextver_0.2.1_macOS_arm64.tar.gz"
      sha256 "25b52e8601d28af98e0722798d9df6c6438a676c5822da265c122fa73b93e0f2"

      def install
        bin.install "nextver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/junk1tm/nextver/releases/download/v0.2.1/nextver_0.2.1_macOS_amd64.tar.gz"
      sha256 "5570b7ef4c5e2524aabdfe1748f2812fcc7587ddab766e05f655512f9eb94f0a"

      def install
        bin.install "nextver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/junk1tm/nextver/releases/download/v0.2.1/nextver_0.2.1_linux_arm64.tar.gz"
      sha256 "ac1324d3f85aaaf8ce44d478bb2aae4520b7706a4f2d79d67b2aa043937ea47e"

      def install
        bin.install "nextver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/junk1tm/nextver/releases/download/v0.2.1/nextver_0.2.1_linux_amd64.tar.gz"
      sha256 "784d27aed2d6b763da00e4420c14e7b852ae835759ebdb867e7350c9972bc24b"

      def install
        bin.install "nextver"
      end
    end
  end
end
